### ISSUE TITLE
KafkaProducer registers for governance as input/source instead of output/sink

### ISSUE THREAD

**Issue by marykomor** [IBMStreams/streamsx.kafka#100]
The KafkaProducer and kafkaConsumer calls a common registerForDataGovernance method in AbstractKafkaOperator to register for governance during initialization. The common method does not differentiate between input vs output type. 

The DataGovernanceUtil#registerForDataGovernance method does take a argument to indicate whether the operator should be registered as input type vs output type.

**Comment by RolefH** [comment]
@marykomor A pull request against develop branch is highly appreciated.

**Comment by RolefH** [comment]
@marykomor can you review this commit, please:
https://github.com/IBMStreams/streamsx.kafka/commit/abf33d2f1afbea2224f66bc01bce07ecd46eab55
It should correct the issue.

**Comment by marykomor** [comment]
Looks good! Approved.

Thanks for the quick turnaround.

**Comment by RolefH** [comment]
fixed in release v1.4.2
