### ISSUE TITLE
Kafka Toolkit v1.3.0

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#11]
The Kafka Toolkit v2.0.0 will support Apache Kafka v0.11.x. The following enhancements to the toolkit need to be performed: 

 * Add transactional messaging support (new in v0.11)
 * Enhance the operator to better handle records that fail to be parsed (new in v0.11)
   * Will likely result in a new parameter (`errorPolicy`?)
 * Add support for including headers in records (new in v0.11)

**Comment by RolefH** [comment]
support for headers will go into v1.3.x.

**Comment by RolefH** [comment]
v1.3.0 is released.
