### ISSUE TITLE
StateHandler calls are being traced at info level?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#118]
Is it intentional that the tracing of drain, checkpoint etc. changed to `info` from `debug`? They seem more like debug or even trace level than info.

https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L919

**Comment by RolefH** [comment]
For intensive testing I changed the level of all relevant traces to `info` because `debug` is too verbose and creates too much data.

Before the toolkit release, the trace levels will be reviewed, espacially also the `CrKafkaConsumerGroupClient` class.
