### ISSUE TITLE
Provide option to skip messages that fail to be parsed

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#12]
In Kafka v0.11, support is being added to "skip" over messages that fail to be parsed (either due to `SerializationException` or some other exception). This functionality is being added here: [KAFKA-4740](https://issues.apache.org/jira/browse/KAFKA-4740).

The operator should provide the user the option to specify how it wants to handle these sorts of errors.

**Comment by cancilla** [comment]
Update: As of today (Sep 18, 2017), the issue regarding how to handle messages that cause a SerializationException to be thrown is still being investigated by the Kafka team.

**Comment by RolefH** [comment]
In Toolkkt version v1.2.3 and current development branch these messages are skipped over. See issue #65 .

**Comment by RolefH** [comment]
We could add a parameter 'parsingErrorPolicy' with enum {skip, useDefault}, and another parameter 'defaultvalue' that enables the user to specify the default value that is used in case of error. Default behavior should be skipping over malformed messages.

**Comment by RolefH** [comment]
Messages that cannot be deserialized are skipped and counted in custom metric **nDroppedMalformedMessages**. Implemented since toolkit version v1.2.3.
