### ISSUE TITLE
Add support for transactional messaging

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#13]
Kafka v0.11 will add support for transactional messaging. More information on this support can be found in [KIP-98](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging). 

The operator should be enhanced to take advantage of this functionality.

**Comment by anthonynassar** [comment]
Hello, any news about the progress on this feature?
Thanks

**Comment by RolefH** [comment]
added to v1.3.0
