### ISSUE TITLE
Add support for including headers in Kafka records

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#14]
Kafka v0.11 will introduce the ability to add record headers to individual records. This support is being added via [KIP-82](https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers).

The operators should be enhanced to allow users to specify headers that should be added to the operators.

**Comment by RolefH** [comment]
Suggest to close this issue. When there is a real requirement, we can think about how to expose headers to the user interface of the operators.
