### ISSUE TITLE
Add an 'isConnected' Custom metric to the operators

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.kafka#168]
The **isConnected** custom metric has a special treatment in the cloud. It creates a warning when it has the value 0.

As the Kafka Java API is very high-level, and does not provide connection handling to the user, we could derive the **isConnected** state from the kafka metric **connection-count**:

Pseudo code:
```
isConnected = connection-count > 0? 1: 0;
```

Care must be taken to avoid a false warning when the producer has not yet produced, or the consumer has not yet assigned partitions. This can happen when the consumer input port is used, or when a pattern subscription is configured, and no topic is matching the pattern.

This issue tracks the implementation of the enhancement in https://github.com/IBMStreams/streamsx.messagehub/issues/93

**Comment by ghost** [comment]
Streams in public cloud is not a priority any more.
