### ISSUE TITLE
KafkaConsumer: assign output attributes via index rather than attribute name

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.kafka#203]
Output attribute assignment is done solely via name. This adds overhead of calculating the hash from the attribute name and hash lookup for each output attribute for each submitted tuple. Determining the attribute index once in `initialize()` and assign attributes via index would be more performant.

https://github.com/IBMStreams/streamsx.kafka/blob/d92513cdd74a86a186074dc8d2d18148735e04e8/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L1029

**Comment by ghost** [comment]
Resolved with [release 3.0.4](https://github.com/IBMStreams/streamsx.kafka/releases/tag/v3.0.4)
