### ISSUE TITLE
Please add the ability to specify target partition to kafka producer

### ISSUE THREAD

**Issue by pavuluri** [IBMStreams/streamsx.kafka#23]
We should be able to specify (optionally) which partition a message should go to when producing messages.  I believe ProducerRecord api can be used for this.   Partition based parallelism is heavily used in our customer engagement, and our producers will have to publish specific keys to specific partitions in this very stateful application.  Appreciate this feature very much.

**Comment by cancilla** [comment]
I have added a new parameter called **partitionAttribute** to the **KafkaProducer** operator. This parameter accepts an `int32` attribute that contains the partition number that the record should be written to. The documentation for this parameter can be found [HERE](https://github.com/IBMStreams/streamsx.kafka/wiki/KafkaProducer-Operator-Design). 

The sample application [KafkaPublishToPartitionSample](https://github.com/IBMStreams/streamsx.kafka/tree/develop/samples/KafkaPublishToPartitionSample) demonstrates how to use this functionality.
