### ISSUE TITLE
Please provide option to pass in client.id as a parameter 

### ISSUE THREAD

**Issue by pavuluri** [IBMStreams/streamsx.kafka#27]
In our customer engagement, we have a very parallel and stateful Streams application.  We achieve parallelism using UDP, and having kafka consumer inside each UDP channel, subscribing to a particular kafka partition, all to the same topic.  Without specifying a client id, we are running into problems - kafka doesn't honor client offsets in this situation.  Each time we start streams application, consumers start from the very beginning of the topic.  Specifying client.id, resolved this problem.   Please add the ability to specify optional client.id.   Thank you.

**Comment by cancilla** [comment]
Done.
