### ISSUE TITLE
Toolkit version is not in adherence with guidelines

### ISSUE THREAD

**Issue by ZollnaPa** [IBMStreams/streamsx.kafka#28]
The version of the toolkit that the info.xml specifies, it is not  in adherence with guidelines: https://github.com/IBMStreams/administration/wiki/Toolkit-Versions
The toolkit has to specify 3 digits only: major, minor and micro. The 4th qualifier is specified for the build identity. It can be set by spl-make-toolkit -i . -v <major.minor.micro.**qualifier**> during the build/release process if required.
Please reduce the digits number in the version attribute that you provide in info.xml

**Comment by cancilla** [comment]
When the toolkit is officially released, it will use the standard 3-digit version as per the [semantic versioning guidelines](http://semver.org). 

The specific versions being released are available on the Kafka Toolkit wiki: https://github.com/IBMStreams/streamsx.kafka/wiki
