### ISSUE TITLE
NLS Resources have been removed from the split Kafka toolkit source files  

### ISSUE THREAD

**Issue by schulz2** [IBMStreams/streamsx.kafka#3]
@cancilla:
I don't know if it was by mistake (an old version of the Messaging toolkit) or by intent:
The resource files and code changesfor National Language Support (NSL) are not in the Kafka toolkit source files split from the Messaging toolkit.

**Comment by ZollnaPa** [comment]
The advantage of the NLS is the centralized collection of all messages. The usage of the NLS interface is very easy so I don't see a reason why the NLS is removed from this toolkit.

The details of NLS are described in following document: https://github.com/IBMStreams/administration/wiki/Messages-and-National-Language-Support-for-toolkits

**Comment by cancilla** [comment]
The toolkit was likely split from a version prior to NLS support being added. Since this toolkit is being used as a reference and not being released, I don't see any issue here.

**Comment by cancilla** [comment]
The Kafka toolkit found in the `develop` branch contains NLS Resources. Closing this issue.
