### ISSUE TITLE
KafkaProducer seems to expect (mandatorily) a key now

### ISSUE THREAD

**Issue by schulz2** [IBMStreams/streamsx.kafka#30]
When running the our "KafkaNoKeyAttribute" regression test we receive the following exception:
>Exception in thread "Thread-13" java.lang.NullPointerException
>	at com.ibm.streamsx.kafka.clients.AbstractKafkaClient.getSerializer(AbstractKafkaClient.java:28)
>	at com.ibm.streamsx.kafka.clients.producer.KafkaProducerClient.<init>(KafkaProducerClient.java:38)
>	at com.ibm.streamsx.kafka.clients.producer.AtLeastOnceKafkaProducerClient.<init>(AtLeastOnceKafkaProducerClient.java:16)
>	at com.ibm.streamsx.kafka.operators.AbstractKafkaProducerOperator.initProducer(AbstractKafkaProducerOperator.java:273)
>	at com.ibm.streamsx.kafka.operators.AbstractKafkaProducerOperator.initialize(AbstractKafkaProducerOperator.java:257)
>	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)

Looking at the code leads to lines where a 'keyType' member is accessed that is connected to handling of 'key' attributes. Thus the current implementation seems to expect to always have a 'key' attribute, while the current Kafka documentation states:

> 
> public class ProducerRecord<K,V>
> extends Object
> 
> A key/value pair to be sent to Kafka. This consists of a topic name to which the record is being sent, an optional partition number, and an optional key and value.
> 
> If a valid partition number is specified that partition will be used when sending the record. If no partition is specified but a key is present a partition will be chosen using a hash of the key. If neither key nor partition is present a partition will be assigned in a round-robin fashion.
> 
> The record also has an associated timestamp. If the user did not provide a timestamp, the producer will stamp the record with its current time. The timestamp eventually used by Kafka depends on the timestamp type configured for the topic. 
> ...

**Comment by cancilla** [comment]
No, the current implementation does not always expect to have a key attribute. There are several places in the operator that determine whether the key attribute is present. The `process()` method will pass `null` if a key is not found. (https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaProducerOperator.java#L300)

The exception above is being thrown when attempting to determine the key serializer to use. This code is missing a `null` check to handle the case where there is no key attribute.
