### ISSUE TITLE
KafkaConsumer: Proposal to add optional input port to allow for dynamically specifying the topic-partition offset to consume from

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#39]
# Use Case
When the KafkaConsumer operator starts, it has the ability to read messages either from the beginning of a topic or the end (via the `startPosition`) parameter. Further, by enabling consistent region support, the operator can begin consuming from the offset position that is saved during a checkpoint operation. 

However, the operator does not currently provide the ability for an application to explicitly specify the offsets that the operator should begin consuming from. This feature is useful when the application is restarted and needs to continue consuming from a previously known offset. In this scenario, the application will need to have stored the previous offset in an external data store (i.e. a database). 

# Proposal

To support this, an *optional* input port will be added to the KafkaConsumer operator to allow applications to dynamically **add** a list of topic-partitions to consume from or to **remove** a list of topic-partitions that should no longer be consumed from. Furthermore, adding and remove topic-partitions will be supported any point during the application's runtime (not just at startup).

## Adding topic-partitions
 * In the case where a user wants to *add* topic partitions, they must provide the following information: 
    * **topic** - topic to subscribe to
    * **partition** - partition to be assigned to
    * **offset** - offset to begin consuming messages from
 * In the event that **offset** provided by the user does not exist, the operator will leave it up to the underlying KafkaConsumer API to decide what to do
    * By default, the KafkaConsumer API will use the `auto.offset.reset` config to either instruct the consumer to begin reading from the beginning of the topic (`earliest` message), the end of the topic (`latest` message) or to throw an `OffsetOutOfRangeException`
 * If the consumer is already assigned to a topic-partition that gets submitted to the input port, the consumer will seek to the new offset (or put another way, the current offset that the consumer is reading from will be overridden by the value submitted via the input port)

## Remove topic-partitions
 * In the case where a user wants to *remove* topic partitions, they must provide the following information:
    * **topic** - topic to unsubscribe from
    * **partition** - partition to unsubscribe from 
 * If the consumer is not assigned to a topic-partition that the user is attempting to remove, then no action is taken

## Input port schema

The input port schema must contain a single `rstring` attribute that accepts a JSON message in order to add or remove a topic-partition. The JSON message will have the following schema: 

```
{
  "action" : ["ADD" | "REMOVE"]
  "topicPartitionOffsets" : [
    {
      "topic" : "topic-name",
      "partition" : <partition_number>,
      "offset" : <offset_number>
    },
    ...
  ]
}
```

Convenience functions will be provided to aid in creating the messages:

```
/* Creates the JSON message to add a single topic-partition to the operator and to begin consuming at the specified offset. */
rstring addTopicPartitionMessage(rstring topic, int32 partition, int64 offset);

/* Creates the JSON message to add multiple topic-partitions to the operator. The operator will begin consuming from the topic-partitions at the specified offset */
rstring addTopicPartitionMessage(list<tuple<rstring topic, int32 partition, int64 offset>> topicPartitionsToAdd);

/* Creates the JSON message to remove a single topic-partition from the operator. */
rstring removeTopicPartitionMessage(rstring topic, int32 partition);

/* Creates the JSON message to remove multiple topic-partitions from the operator. */
rstring removeTopicPartitionMessage(list<tuple<rstring topic, int32 partition>> topicPartitionsToRemove);
```

## Limitations

The following limitations will apply: 
  * When the input port is specified, the `topic`, `partitions` and `startPosition` parameters should not be defined (a warning will be displayed during compile-time that these parameter values will be ignored). Topics and partitions to consume from must be specified by submitting a tuple to the input port.
  * When the input port is specified, the operator will not begin consuming messages until at least one tuple is received on the input port that **add**s a topic-partition
 

# Compatibility

The above proposal **will not** break compatibility with existing applications. 

## SPL Examples

The following are examples of possible SPL applications that add or remove topic-partitions:

#### Add topic partitions
```
        (stream<TopicPartitionsOffsetUpdate> TopicPartitionUpdateStream) as TopicPartitionUpdater = Custom()
        {
            logic
                onProcess:
                {
                    rstring addSingleTopicMessage = addTopicPartitionMessage("test1", 0, 90l);
                    submit({jsonString = addSingleTopicMessage}, TopicPartitionUpdateStream);

                    rstring addMultipleTopicsMessage = addTopicPartitionMessage([
                      {topic="test1", partition=1, offset=100l},
                      {topic="test2", partition=0, offset=0l}
                    ])
                    submit({jsonString = addMultipleTopicsMessage}, TopicPartitionUpdateStream);               
                }
        }
    
        (stream<rstring message> MessageOutStream) as KafkaConsumerOp =
            KafkaConsumer(TopicPartitionUpdateStream)
        {
            param
                propertiesFile : getThisToolkitDir() +
                    "/etc/consumer.properties" ;
        }
```
 
#### Remove topic-partitions
*NOTE:* The offset value doesn't matter since the topic-partitions are being removed. 

```
        (stream<TopicPartitionsOffsetUpdate> TopicPartitionUpdateStream) as TopicPartitionUpdater = Custom()
        {
            logic
                onProcess:
                {
                    rstring removeSingleTopicMessage = removeTopicPartitionMessage("test1", 0);
                    submit({jsonString = removeSingleTopicMessage}, TopicPartitionUpdateStream);

                    rstring removeMultipleTopicsMessage = removeTopicPartitionMessage([
                      {topic="test1", partition=1},
                      {topic="test2", partition=0}
                    ])
                    submit({jsonString = removeMultipleTopicsMessage}, TopicPartitionUpdateStream);  
                }
        }
    
        (stream<rstring message> MessageOutStream) as KafkaConsumerOp =
            KafkaConsumer(TopicPartitionUpdateStream)
        {
            param
                propertiesFile : getThisToolkitDir() +
                    "/etc/consumer.properties" ;
        }
```

**Comment by ddebrunner** [comment]
Consider using/allowing JSON as the port's scheme, as a control port this allows for future feature additions without breaking existing applications.

**Comment by ddebrunner** [comment]
Somewhat relates to https://github.com/IBMStreams/streamsx.messaging/issues/291

**Comment by cancilla** [comment]
Updated the proposal to use a JSON schema rather than SPL-defined types

**Comment by cancilla** [comment]
Completed in v1.2.0
