### ISSUE TITLE
Discussion: Specifying Kafka configurations

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#4]
The producer and consumer APIs that are provided by Apache Kafka contain numerous configuration options that can change how the operators interact with the Kafka cluster. How these configuration options are specified is a vital part of using these operators within a Stream application.

### Goals
In this post, I would like to propose a solution for allowing users to specify Kafka configuration within the context of a Kafka operator This proposal attempts to make it possible for the operators to be configured in any one of the following scenarios: 

  1. Allow the user to provide a set of Kafka properties via a file 
  2. Allow the user to configure an operator to connect to MessageHub with as little effort as possible
  3. Allow the user to provide Kafka configurations via Streams application configurations
      * Support specifying multiple app configs, so different configs can be shared
      * Support specifying MessageHub credentials via an app config
  4. Allow the user to specify Kafka configurations at submission-time via a parameter  
  5. (Forward-looking) When running on Bluemix, if the MessageHub service is bound to the Streaming Analytics service (this is not possible as of this writing), operators should automatically be able to determine the MessageHub credentials from the VCAP env var and connect to MessageHub.  
  
### Solution
In order to achieve the above goals, the following options for specifying the configurations will be available in the operator:

  * The `propertiesFile` parameter will be used to specify a properties file containing kafka configurations
    * Multiple properties files can be specified to allow for having "shared" configurations between different Kafka operators in the same application
  * The `messageHubCredFile` parameter will be used to specify the file containing the credentials for a MessageHub service
  * The `appConfigNames` parameter will be used to specify one or more application configurations containing Kafka properties
    * All properties stored in the application configurations specified will be loaded as Kafka configurations. This means that the property names must match the names of the Kafka configurations.
    * Multiple application configurations can be specified to enable having both shared and application-specific app configs
    * A special "message_hub.credentials" property can be specified in an app config to allow users to easily create a connection to a MessageHub service.
  * The `kafkaProperties` parameter will be used to allow the user to specify configurations at submission-time (the user could also hard-code configurations using this property)
  * (Forward-looking) The operator will be able to retrieve the MessageHub credentials from the VCAP system environment variable and connect to that MessageHub service.
    * Since it is not currently possible to bind a MessageHub service to a Streaming Analytics service, no further details will be provided at this time for how this will be done. This option is being included here so that if this type of binding ever becomes possible, the operators can be updated with minimal effort to support this functionality. 

#### Running in BlueMix
One of the primary goals of this document is to make it as simple as possible to run these operators in a BlueMix environment. To that end, the operators will provide 2 options for specifying the MessageHub credentials: 

  * Via the `messageHubCredFile` parameter
    * Points to a file containing the entire contents of the MessageHub credentials, pasted verbatim
  * Via the `message_hub.credentials` app config property
    * This value of this property will contain the entire contents of the MessageHub credentials, pasted verbatim

The operator will perform in the following way when MessageHub credentials are read in: 

  * The operator will parse out the necessary information from these credentials and set the appropriate configuration options to allow the operator to connect.
  * At a minimum, the user *will not* need to provide any additional configurations to allow the operators to connect
    * If necessary, additional configuration options can be specified using any of the other methods (i.e. via app config, properties files, etc)
  

#### Property Precedence
The precedence for reading Kafka configurations from the various locations will be done in descending order starting from "most easily changed at submission-time". This means that during operator initialization, the Kafka configurations will be loaded from the following locations in the given order. If duplicate properties are found, the value from the **first** property read will be used.

 1. Submission-time value
 2. Application configuration (if running distributed)
 3. VCAP system env variable
 4. MessageHub credentials file
 5. Properties files

#### SASL/JAAS
Kafka v0.10 introduced a new property called **sasl.jaas.config**, which allows users to pass in their JAAS credentials as a property value rather than using a Java system property to point to a file. This property will enable multiple Kafka operators to run within the same JVM but potentially connect to different secured Kafka clusters. 

The new set of Kafka operators will eliminate the `jaasFile` and `jaasFilePropName` parameters and encourage users to specify their JAAS credentials via this property. 

Furthermore, when connecting to a Bluemix environment using the MessageHub credentials, the Kafka operators will construct the necessary the value for the **sasl.jaas.config** property, eliminating the need for users to have to build/manage their own JAAS files.

**Comment by ddebrunner** [comment]
What would the format of the submission time value be?

**Comment by ddebrunner** [comment]
Maybe rather than trying to have all these options on a single operator, maybe Kafka Producer/Consumer operator that handles the low-level properties and MessageHub Producer/Consumer wrappers that are only intended to support MessageHub and have their configuration focussed on that.

**Comment by Alex-Cook4** [comment]
What would be the method for providing the username/password required in the jaas.conf file for the Message Hub login? One solution that I haven't tried out might be to leverage the new [sasl.jaas.config](https://cwiki.apache.org/confluence/display/KAFKA/KIP-85%3A+Dynamic+JAAS+configuration+for+Kafka+clients) Kafka Property. Discussion about this is [here](https://github.com/IBMStreams/streamsx.messaging/issues/278).

**Comment by Alex-Cook4** [comment]
+1 to the idea of MessageHub-only wrappers. This would help make a virtually fool-proof operator for that case.

**Comment by cancilla** [comment]
@Alex-Cook4 Sorry, I forgot to mention the JAAS config in the above proposal. My plan is to eliminate the `jaasFile` and `jaasFilePropName` parameters and use the **sasl.jaas.config** property that you mentioned. I already prototyped this in my workspace and I am able to connect to MessageHub same as before. More interestingly, I am able to construct the value for this property using only the information provided in the MessageHub creds. This means users will no longer have to deal with JAAS files when connecting to MessageHub. 

Users connecting to a secured on-prem Kafka cluster will still need to provide JAAS information, but they can pass in that info using the sasl.jaas.config property rather than as a separate file.

**Comment by Alex-Cook4** [comment]
Excellent! Yes, I didn't realize that everything is in the credentials file now. That will make this so much easier. 

I think @ddebrunner has done this before with the MQTT operators, but this would allow us to upload .sab files that just take a submission-time parameter or AppConfig to connect to MessageHub, then just have a publish/subscribe way for other Streams apps to get and write to MessageHub. Maybe that's obvious, but I find it exciting!

**Comment by ddebrunner** [comment]
> For the submission-time value, I was planning to keep it as a list of key=value pairs (same as the existing Kafka operators)

Just seems like that's going to be pretty ugly to enter as a submission time value.

I can see why a submission value might be an idea, but at least for distributed/bluemix using an application configuration is a better approach.  Then one has a submission parameter that provides the app config name rather than the actual configuration.

**Comment by ddebrunner** [comment]
I think we need to be careful about trying to cover every possible situation and making the configuration too complex, thus making the operator harder to use. Having five levels of finding config information with some having multiple entries might be over thinking the problem.

It's also important to note that there are (I think) two types of kafka configuration items:

1. Information to identify the Kafka broker
1. Configuration for the *application*, e.g. the setting for ensuring the message makes it to all brokers.

The second set should not be overwritten by configuration since it changes the application behaviour, e.g. breaking consistent region guarantees.

As @Alex-Cook4 pointed out, for MessageHub I want a simple foolproof way to connect to it, ideally a single parameter, which app config to use, maybe even defaulting to one named "message-hub".

**Comment by ddebrunner** [comment]
Java primitive or composite is really an implementation detail, though if the operator has knowledge of submission time parameters it has to be a composite.

I would be somewhat wary of adding support for submission time value support in an operator, it means that the operator always exposes ways to change its configuration, thus no longer left up to the application to decide. A microservice that exposes submission time value is fine, an operator I'm not so sure about, submission time values are really the application's responsibility.

**Comment by cancilla** [comment]
> Just seems like that's going to be pretty ugly to enter as a submission time value.
> 
> I can see why a submission value might be an idea, but at least for distributed/bluemix using an application configuration is a better approach. Then one has a submission parameter that provides the app config name rather than the actual configuration.

@ddebrunner I agree that app configs make more sense. The use cases I have in mind for this are:

 1. Running an app in standalone
 2. Using the operators in a Java topology that is submitted using an Embedded context

In both cases, the submission-time parameter provides a straight-forward way to dynamically/programmatically set things like brokers or to test different property values.

**Comment by cancilla** [comment]
> I think we need to be careful about trying to cover every possible situation and making the configuration too complex, thus making the operator harder to use. Having five levels of finding config information with some having multiple entries might be over thinking the problem.

That's a good point. I think we'll start without the `kafkaProperty` parameter and if someone presents a valid need for it, we can add it back in. It always easier to add something to the operators than to remove it.

**Comment by cancilla** [comment]
> It's also important to note that there are (I think) two types of kafka configuration items:
> 
> 1. Information to identify the Kafka broker
> 1. Configuration for the *application*, e.g. the setting for ensuring the message makes it to all brokers.

The problem is that Kafka doesn't make this sort of distinction...everything is a property, whether it's setting the brokers, setting up creds or changing app behaviour. I worry about trying to invent categories (connectivity vs app config) for the different properties and then treating those properties in a different way.

**Comment by ddebrunner** [comment]
@cancilla Maybe the same case for multple configuration items., e.g. multiple application configurations. What would you expect to be in each app config?

**Comment by ddebrunner** [comment]
> I worry about trying to invent categories (connectivity vs app config) for the different properties

That wasn't what I meant, but instead the app should be able to have the last word in setting properties, so if it sets `some_kafka_property='a'` then that wins.

**Comment by cancilla** [comment]
> That wasn't what I meant, but instead the app should be able to have the last word in setting properties, so if it sets some_kafka_property='a' then that wins.

Let me see if I understand your point. You are suggesting that app config should primarily be used for setting things that will be the same across applications, such as broker urls or credentials. For other properties that affect how the application works (i.e. acks=all or buffer.size=whatever), the application should be allowed to set (or override) these properties as needed.

This boils down to a couple of things then: 

 1. The property precedence should be changed such that properties set at the application level take precedence over the properties set at the app config level
 2. Documentation on the best practices when using these operators

**Comment by cancilla** [comment]
Thanks for the feedback! As per the discussion, the operators will: 

 * allow properties to be specified either via an `appConfig` or `propertiesFile`
 * properties specified via a `propertiesFile` will override any properties specified in an `appConfig`
 * A separate repo and toolkit have been created to for MessageHub operators
