### ISSUE TITLE
KafkaConsumer: Proposal to (optionally) output offset, partition and timestamp values with each message

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#40]
# Use Case

Currently, the operator is capable of populating tuple attributes with the `message`, `key` and `topic` values for a given record. The operator should also be capable of populating tuple attributes with the `offset`, `partition` and `timestamp` values. 

# Proposal

In order to support the above use case, the following operator parameters will be added:

| Parameter Name | SPL Type | Default | Description | 
| --- | --- | --- | --- |
| outputOffsetAttributeName | int64 | `offset` | Specifies the output attribute name that should contain the offset. If not specified, the operator will attempt to store the message in an attribute named 'offset'. |
| outputPartitionAttributeName | int32 | `partition` | Specifies the output attribute name that should contain the partition. If not specified, the operator will attempt to store the message in an attribute named 'partition'. |
| outputTimestampAttributeName | int64 | `messageTimestamp` | Specifies the output attribute name that should contain the record's timestamp. If not specified, the operator will attempt to store the message in an attribute named 'messageTimestamp'. |

# Compatibility 

The proposed changes **will not** break compatibility with existing applications.

**Comment by ddebrunner** [comment]
What is the record's timestamp? When added to the queue, set by an app, when taken from a queue?

**Comment by ddebrunner** [comment]
Somewhat relates to https://github.com/IBMStreams/streamsx.messaging/issues/291

**Comment by cancilla** [comment]
By default, Kafka sets the message timestamp as the "creation" time in epoch seconds. This is stored as a `long` type.

**Comment by ddebrunner** [comment]
Really, the long represents number of seconds since the unix epoch, or the number of milliseconds?

**Comment by cancilla** [comment]
Correction, I meant milliseconds.

**Comment by cancilla** [comment]
Completed in v1.2.0
