### ISSUE TITLE
KafkaConsumer: triggerCount should specify the exact value for initiating a checkpoint

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#45]
In the current implementation of the `triggerCount` parameter, the value specified by the user will be the minimum number of tuples that will be submitted prior to initiating a checkpoint. This implies that the actual number of tuples that get submitted before the operator is checkpointed is not deterministic. 

The `KafkaConsumer` operator needs to be enhanced so that the value specified for `triggerCount` represents the exact number of tuples that will be submitted prior to a checkpoint.

**Comment by cancilla** [comment]
Fixed in v1.2.0

**Comment by ddebrunner** [comment]
What's the rationale for requiring the number be fixed?

I'm looking at if this change broke the operator at least once guarantee in a consistent region.
