### ISSUE TITLE
Bad bounds check can cause exception

### ISSUE THREAD

**Issue by andrewstreams** [IBMStreams/streamsx.kafka#46]
The bounds check here isn't sufficient for the next step:

https://github.com/IBMStreams/streamsx.kafka/blob/61e1f3d3b1316205cd15360fb34a10a07958957e/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/clients/consumer/KafkaConsumerClient.java#L301

It confirms there is space for at least 1 element, but then pulls a complete bundle. If there's not enough space (e.g. high rate streams, or backpressure from downstream) then an exception is thrown and the operator crashes and restarts. Probably the check needs to be improved, or possibly the returned items need to be cached if there's not enough space.

**Comment by cancilla** [comment]
Good catch! In v1.1.1, the messageQueue was storing the `ConsumerRecords`object, so their was either room or there wasn't. In v1.2, this was changed such that messageQueue now stores each individual `ConsumerRecord`. 

At first glance (on a Friday afternoon), perhaps the operator should check if the remainingCapacity is at least the size specified by `max.poll.records`. This should guarantee that the queue has enough space for each of the `ConsumerRecord`s retrieved.

Thank you for reporting this issue.

**Comment by cancilla** [comment]
Fixed via commit 5eef2b0
