### ISSUE TITLE
Support kafkaProperty parameters

### ISSUE THREAD

**Issue by andrewstreams** [IBMStreams/streamsx.kafka#47]
The deprecated Kafka operators in streamsx.messaging supported providing parameters in the SPL file as well as a properties file. This allowed using a single properties file for multiple consumers, and overriding specific parameters either statically at runtime, for example the consumer group ID. Please consider supporting that in these operators through addition of such a parameter.

**Comment by cancilla** [comment]
Similar functionality can be achieved using application configurations. Common parameters can be set in one or more application configurations, which can be specified at runtime. I have thought introducing an operator parameter to allow for getting the group ID directly in the SPL (similar to the clientID parameter).

**Comment by andrewstreams** [comment]
Thanks for the information - I was thinking of using the application configuration to hold all the details specific to that cluster (my application runs in multiple clusters with different parameters) but that still needs me wanting a way to have the group ID differ between jobs without a new application config every time. I think the group ID is the only parameter I'd want to set this way, and supporting it explicitly might make it clearer for users, so I'd be supportive of that option.

**Comment by RolefH** [comment]
This issue can be closed as the preference of configuration options is described in SPL doc:
- properties file over-rules app option
- parameter (clientId, groupId since v1.3.0) over-rules properties file
