### ISSUE TITLE
ConnectionState.java:org.apache.curator.ConnectionState.checkState - Authentication faile

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.kafka#49]
kafka version 0.10 ( zookeeper of kafka with kerberos authentication)
     streams version 4.2.1.2
     com.ibm.streamx.kafka version : 1.1.1 ( I add the code to pass the kerberos)

     the function of KafkaConsumer and KafkaProducer work well.    

    but when use KafkaConsumer, there was following eror in the pe.out.
   SPL:
               (stream<rstring message> KafkaStream_GnData_Out) as KafkaStream_GnData = KafkaConsumer()
                {
                        param
                                topic: "B_EBU_GSM_NEW";
                                propertiesFile  : "/home/streamimcdad/conf/consumer.properties" ;
                }
                () as SinkOp = Custom(KafkaStream_GnData_Out)
                {
                        logic
                                onTuple KafkaStream_GnData_Out : {
                                        println("message-->"+ message);
                                }
                }

12 Oct 2017 17:43:06.704 [32515] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:07.753 [32524] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:08.807 [32534] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:09.859 [32540] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:10.907 [32547] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:11.939 [32558] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:12.973 [32563] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:14.015 [32571] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:15.070 [32590] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
12 Oct 2017 17:43:16.130 [32643] ERROR #splapptrc,J[42],P[67],SinkOp M[ConnectionState.java:org.apache.curator.ConnectionState.checkState:245]  - Authentication failed
![image](https://user-images.githubusercontent.com/11512674/31489870-c7021a4a-af07-11e7-9120-9f92b005d707.png)

**Comment by RolefH** [comment]
I assume, this can be closed.
