### ISSUE TITLE
Add metrics isConnected and reconnectionAttempts

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.kafka#50]
metrics would be helpful for the user to see if the operator is connected or not, for example in Streams Console.

**Comment by schulz2** [comment]
+1

**Comment by cancilla** [comment]
Checking if a Kafka operator is connected is not straight-forward. The Kafka lib doesn't provide any type of `isConnected` API calls. 

I initially thought about using the "connection-count" metric to determine if a connection has been established, but this metric is not reliable. For example, when the Consumer is fetching messages, the value of this metric is `3` (I don't know why there are 3 connections). Now, if I point the Consumer to a URL with the wrong port number, the value of this metric is `1` (again, I'm not sure why...maybe it's waiting for a response?). I am concerned this metric is going to give the wrong impression and I don't think we should rely on it. 

I also considered looking at incoming/outgoing byte rates, but I'm not sure that tells much more than the tuple flow rate metrics that are already built into the operators. 

A list of available metrics can be found here: http://kafka.apache.org/documentation.html#monitoring. I am open to any suggestions.

**Comment by ddebrunner** [comment]
@RolefH  What was the resolution?
