### ISSUE TITLE
KafkaConsumer never updates offsets in a periodic consistent region.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#53]
Changes made for #45 changed the way the offsets were saved through `OffsetManager` for a consistent region in `operatorDriven` mode to be the last message submitted. This then removed any drain processing that previously submitted all the messages  currently on `messageQueue`.

However, when the consistent region is `periodic` there is no mechanism to update `offsetManager` so it remains fixed at the earliest offset. Thus while this will result in "at least once" it's really inefficient and might break once the initial offset has disappeared (maybe not, would have to check). It's inefficient because every reset will cause a re-read of all messages since the start, not just those since the last successful cut.

Fix could be one of:
 * Remove `isTriggerOperator()`  here:  https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L328
 * Reimplement drain as it was previously but only when `isStartOfRegion() && !isTriggerOperator()`.

**Comment by ddebrunner** [comment]
Regardless the drain() method should be commented to indicate why it is not draining the `messageQueue` as would be naturally expected. That's what led me to look at this potential problem initially.

**Comment by RolefH** [comment]
I tend to correct this in the `produceTuples()` function that pulls records from the Message queue rather than to reimplement `drain()`.

**Comment by RolefH** [comment]
corrected in release v1.2.3
