### ISSUE TITLE
KafkaConsumer: Add documentation for the common usage scenarios.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#54]
I think there are two common modes for the consumer that are essential to document, and then two "more advanced" modes that could also be documented. This would make it easier for folks to use the operators when using message hub, i.e. those who are not kafka experts.

By document I mean explain the model of how topics/partitions are matched to consumer operators and example SPL invocations in those modes.

Simple modes:
* Single consumer consuming all partitions.
* Consumer in a UDP region with each individual consumer being automatically assigned partitions.

More advanced
 * UDP region with manually assigned partitions - Does this mean the width must not change?
 * Manual invocation of multiple operators (non-UDP) with manually assigned partitions.

We should probably push the simple approaches as the way to go.

Also some documentation on handling keyed partitions and maintaining the key through SPL UDP regions.

Explanations and examples could be added to `namespace-info.spl` see #37

**Comment by ddebrunner** [comment]
Also, especially how these modes work with consistent region.

**Comment by ddebrunner** [comment]
I started writing this up in the wiki: https://github.com/IBMStreams/streamsx.messagehub/wiki/Standard-Use-Cases-with-partitions

**Comment by RolefH** [comment]
https://ibmstreams.github.io/streamsx.messagehub/docs/user/overview/
https://ibmstreams.github.io/streamsx.kafka/docs/user/overview/

These links are also referenced from the `KafkaConsumer` and `MessageHubConsumer` SPLDoc since toolkit versions v1.5.1.
