### ISSUE TITLE
KafkaConsumer: Permit acquisition needs to be outside the try block.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#58]
The permit acquire is in the same try block as the one that releases it. In the case of an exception while getting the permit, then it will be released even though it was not acquired.

https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L468

**Comment by RolefH** [comment]
corrected in release v1.2.3
