### ISSUE TITLE
KafkaConsumer: Remove resettingLatch as not required (NEED TO VERIFY)

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#59]
I believe permits handle this sitaution, there is no need to have additional synchronization to wait for a reset. I will verify.

https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L456

**Comment by RolefH** [comment]
Synchronization between the tuple producer thread and initial reset is necessary.
I observed following startup sequence after killing the consumer operator:

1. `operator.initialize(context)`
1. `operator.allPortsReady()` notification
    1. `allPortsReady` starts the tuple producer thread
    1. This thread performs
        * `consistentRegionContext.acquirePermit()` - succeeds
        * initializes polling for Kafka messages --> they start filling up the message queue
        * go into endless-loop for acquirePermit() - fetch records from message queue - submit tuples
1. `operator.resetToInitialState()`

The 'resettingLatch' has been used to avoid submitting tuples before the operator was reset to initial or checkpointed state when the operator's PE is relaunched. `acquirePermit()` does not handle this situation.

When *not* in consistent region, operator reset happens after `operator.initialize(context)` and before `allPortsReady()` notification. Here no synchronization is required.

I will revert commit 475fa11 and close this issue.
