### ISSUE TITLE
KafkaProducer: reset handling is confusing.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#62]
When the operator is reset to a checkpoint or its initial state it always closes its `KafkaProducerClient` and then creates a new one. It's then unclear why a `resetToInitialState` method is needed on `KafkaProducerClient` since it's a new object.

Further confusing is that the only implementation for `resetToInitialState` is in `ExactlyOnceKafkaProducerClient` which states it aborts the current transaction, **but** `initTransations()` has just been called which states **it** aborts transactions.

In addition having a `reset` method is confusing as it's not resetting the object (since it's a new object), it's setting up the object. 

Just looking at the producer clients I was expecting to see outstanding messages being cancelled in the reset methods, since that would be the correct, so that's why I started to get confused.

**Comment by RolefH** [comment]
Indeed, a method `resetToInitialState` is not necessary, when the operator instantiates a new producer client in  its own `resetToInitialState()`. A new instance is in initial state.

**Comment by RolefH** [comment]
fixed in release v1.3.0
