### ISSUE TITLE
KafkaProducer: reset handling cancel records?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#63]
Reset handling classes producer.close() which in turn calls `KafkaProducer.close()` which waits for all records to be sent (up to the timeout). This is the incorrect behaviour for a reset, ideally we want to abort any outstanding sends.

For the at least once producer client I wonder if `cancel()` should be called on each future in `futureList`.

For the exactly once I can't image that waiting to flush existing records it the correct approach, though I don't understand the exactly once approach yet.

**Comment by RolefH** [comment]
"Exactly once" is not exactly once. The Java class `ExactlyOnceKafkaProducerClient` should be renamed to `TransactionalKafkaProducerClient`. It is _transactional_, but not _exacly once_.

The approach for exactly once is, that all messages are inserted into a topic within a single transaction. On `checkpoint`, the transaction is committed, on `reset` it is aborted. It is transactional for the producer of a topic and may be exactly once for a client that consumes the same topic.

For the producer, it is impossible to remove messages from a topic when a transaction is aborted (reset of a CR). There is no rollback API for a Kafka transaction. A Kafka client that consumes with default `isolation.level` config (which is `read_uncommited`) will read duplicate messages when a transaction is aborted and tuple reply occurs. Only those clients that consume with configuration `isolation.level = read_committed` it will consume no duplicates.

Cancelling all outstanding requests on `reset` does not help to get exactly once _in terms of inserting messages_ into a topic. Also not flushing the producer does not change things.

**Comment by RolefH** [comment]
fixed in release v1.3.0 with `tryCancelOutstandingSendRequests(...)` at the `TransactionalProducerClient`, which is called in operator's `reset(...)` and `resetToInitialState()` methods.

    @Override
    public void tryCancelOutstandingSendRequests (boolean mayInterruptIfRunning) {
        if (logger.isDebugEnabled()) logger.debug("TransactionalKafkaProducerClient -- trying to cancel requests");
        int nCancelled = 0;
        for (Future<RecordMetadata> future : futuresList) {
            if (!future.isDone() && future.cancel (mayInterruptIfRunning)) ++nCancelled;
        }
        if (logger.isDebugEnabled()) logger.debug("TransactionalKafkaProducerClient -- number of cancelled send requests: " + nCancelled); //$NON-NLS-1$
        futuresList.clear();
    }
