### ISSUE TITLE
Create a branch for 1.2.x releases

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#64]
Is a release branch needed for 1.2.x to fix various issues:

#53 , #57, #58, #59 (?), #60  etc.

**Comment by RolefH** [comment]
The fixes should go into 1.3.0 release. Transactional producer is a new feature, so it's not a v1.2.x. Before branching out, I want to fix most important issues in develop branch.

**Comment by ddebrunner** [comment]
I think we need a 1.2.x release with these fixes. I'm not sure the Transactional producer is ready for release.

**Comment by ddebrunner** [comment]
Most likely the product will need a 1.2.x version to avoid adding new functionality in a fix release.
