### ISSUE TITLE
How can KafkaProducer write to multiple partitions?

### ISSUE THREAD

**Issue by AlexCYang** [IBMStreams/streamsx.kafka#73]
Hi I'm using KafkaProducer from this toolkit with Kakfa 0.9. The issue I'm having is that it only writes to one partition, and our load is not well balanced. So I'm wondering is there a config that I can set so that it will write to multiple partitions? Thanks!

**Comment by schulz2** [comment]
Hello Cheng,
the first thing to keep in mind is, that the toolkit is used (tested) with Kafka v0.10 onwards. I'm not that deep into Kafka's change log to know if something in the way partitioning works changed between v0.9 and v0.10.
That said, as far as I understand Kafka's behavior, it is Kafka itself that decides to which partition a message is written, so a single KafkaProducer connected to a Kafka topic with several partitions shall write to all partitions by default.
Furthermore, the operator has a parameter called "partitionAttribute" and its description states:
"Specifies the input attribute that contains the partition number that the message should be written to. If this parameter is not specified, the operator will look for an input attribute named **partition**. If the user does not indicate which partition the message should be written to, then Kafka's default partitioning strategy will be used instead (partition based on the specified partitioner or in a round-robin fashion)."

This leaves you with the following options:
- Introduce a "partition" attribute into your tuple to define where that tuple shall end.
- If you already have such information in a different attribute use the "partitionAttribute"
- Check the partitioning configuration of your Kafka server
- Run against Kafka v0.10 (or newer)
- Use the old/deprecated Kafka operator in streamsx.messaging against Kafka v0.9
(The list is not prioritized)

Hope that helps.

Kind regards
Norbert

**Comment by AlexCYang** [comment]
Thanks for the quick reply Norbert!

Actually we are using the deprecated Kafka operator in streamsx.messaging because our Kafka cluster is on version 0.9 and we need to support that. I noticed that Kafka is deprecated there so I'm asking the question here. Sorry I didn't read the code in detail before and I assumed there's not many code changes between these two toolkits.

After reading your reply I went to the code and see there're attributes relates to 'partition' in KafkaProducer in the streamsx.kafka toolkit and the functions to write to Kakfa will take partition into consideration, but the KafkaProducer part in streams.messaging does not have anything related to partition. Is there anything I can do on the old KakfaProducer in streamsx.messaging that will allow us write to multiple partitions? I'm thinking of writing and setting my own partitioner class in PARTITIONER_CLASS_CONFIG but before that I'm hoping to get some advice here.

Thanks!

Cheng

**Comment by AlexCYang** [comment]
After looking at the default partitioner by Kafka, the hash of the key attribute is actually used for partition by default. And in our case, the key is limited(usually less than 6, or sometimes event just 1), so the hashing will give us less than 6 partitions and sometimes just 1 partition. So we are going to rewrite a partitioner class to suit our need. 

Thanks!
