### ISSUE TITLE
Kafka's at-least-once (restart at last committed offset) - not supported

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.kafka#76]
Kafka claims that is supports at-least-once consuming of records. When a consumer has processed data it should commit offsets of that data. If a consumer dies it will be able to start up and start reading where it left off based on the offsets stored in __consumer_offset.

This simple basic Kafka use case is not supported when a Streams application is tightly fused without extra threads in between. Such an application will always miss Kafka messages on restart.
The KafkaConsumer is designed with an internal message queue, that is filled by thread A. This thread commits the offset after insertion into the queue. Thread B reads the queue and submits tuples. When the PE dies or is shutdown gracefully, the messages in the queue are committed, but lost. When the operator restarts, it will start reading after last committed offset, but not after the offset of the last submitted tuple.

**Two requirements:**
1. The KafkaConsumer should commit offsets after the tuples have been submitted. Then there is a *chance* of at-least-once.
1. The KafkaConsumer should generate a window marker when a batch of Kafka messages have been committed. The window marker in the outgoing stream then has the semantics. All tuples (== Kafka messages) before the marker are committed.

**Two options to achieve this**
1. Remove the internal message queue in the operator. Submit the tuples directly from the thread that consumes Kafka messages.
1. Leave the queue, but send a commit request from thread B through the command queue to thread A. Implement thread synchronisation between these threads to ensure that commit really happened by thread A before thread B continues submitting tuples

The second option is rather complicated, so that I vote for the first option.

**Comment by ddebrunner** [comment]
From a Streams application point of view what problem is being solved or what use-case is being addressed here? I'm wary of adding additional modes to the consumer when the existing use-case modes are not well articulated. For example the first requirement is an implementation statement, not a behaviour requirement.

If this is trying to address the case of an application fused into a single PE with manual threading specified, no threaded ports, no background activity I'm not sure that's a use case we want to really prioritize.

**Comment by RolefH** [comment]
This is what users often ask: Can we start reading at the position where we left off? And I must say, "no, we can't - even in the simplest scenario".

**Comment by RolefH** [comment]
option 2 implemented in v1.4.0 with asynchronous commit
