### ISSUE TITLE
Consumer op is tracing per tuple at debug level.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#88]
Recommendation is to log per tuple activity at trace level.

In addition this same trace is logging the tuple contents to application trace, this not not ok as it means potentially sensitive information can end up in the log.

https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L645

Also, please note that the SPL runtime already logs tuple submission at trace level, there is no need for operators to also do that.

**Comment by RolefH** [comment]
fixed with v1.3.3
