### ISSUE TITLE
KafkaConsumer can hit OutOfMemoryException.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#91]
With large messages and when the consumer is faster than downstream processing (or there is a spike in messages) the message queue can start to fill up, thus consuming memory.

With a test case of ~12KB messages and the default settings for the operator and JVM an OutOfMemoryException is hit around ~22,000 messages. The default queue capacity is 50,000 messages.

While this can be worked around with changing the max memory for the VM or the max polled records, it's possible for the operator to detect low memory and react.

I have code that detects this situation and pauses the operator similar to the way it pauses today if the queue is full. In this case the queue stabilized with about 18,000 messages and no OutOfMemoryException.

I also added a couple of metrics:

![image](https://user-images.githubusercontent.com/3769612/40089430-97f52a78-5860-11e8-97f7-f1d0c424e7a1.png)

**Comment by ddebrunner** [comment]
Follow on to #90

I'll create a pull request tomorrow.

**Comment by RolefH** [comment]
re-opened because this fix is in no release yet - only in develop branch

**Comment by RolefH** [comment]
resolved with toolkit version 1.4.0

**Comment by RolefH** [comment]
With large `max.partition.fetch.bytes` consumer configuration the memory monitoring before fetching messages is not sufficient.
Tested with `max.partition.fetch.bytes = 20971520` and message blobs of 1MByte size.

```
[com.ibm.streams.operator.internal.jni.JNIBridge.complete:-1]  - Java heap space
  - java.lang.OutOfMemoryError: Java heap space
  - java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
  - java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
  - org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
  - org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:112)
  - org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
  - org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
  - org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
  - org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
  - org.apache.kafka.common.network.Selector.poll(Selector.java:467)
  - org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:535)
  - org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
  - org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
  - org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1243)
  - org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1188)
  - org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1123)
  - com.ibm.streamsx.kafka.clients.consumer.AbstractNonCrKafkaConsumerClient.pollAndEnqueue(AbstractNonCrKafkaConsumerClient.java:378)
...
```
The stack trace shows that the OOM occurs when the buffer for the fetch result is allocated.
Shortly before, the Heartbeat thread dies with OOM:
```
  - java.lang.OutOfMemoryError: Java heap space
  -   at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
  -   at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
  -   at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
  -   at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:112)
  -   at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:381)
  -   at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:342)
  -   at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:609)
  -   at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:541)
  -   at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
  -   at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:535)
  -   at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
  -   at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:304)
  -   at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:996)
```

**Comment by RolefH** [comment]
The point here is, that the memory check (max memory, total memory, free memory) is done only when the mesage queue is filled by more than `4 * max.poll.records`, in default configuration, this is 2000. With 1M messages, we see out of memory at a queue fill of ~330 (far before any memory is checked).
Doing the memory check _always_ (We can be short of memory always for any reason!), increases CPU utilization by ~20% reducing maximum throughput. by the same factor.

The current minimum required free memory for doing a fetch is currently `maxMemory * 0.1`, which is ~51 MB. This is ~ `fetch.max.bytes` default value.

Suggestions:
1. check memory earlier: when queue size is > `max.poll.records`, **not** when size > 4*max.poll.records
1. add an absolute minimum free memory. Free memory must be more than `2 * fetch.max.bytes` or 10% of max memory. The factor 2 is for safety.
1. In case we receive compressed messages, the required memory can be significantly more than fetch.max.bytes. Decompression happens after the messages are fetched. For this case we must be capable to overwrite the minimum free memory. I suggest to use a property that is given as vmArg. When this is required, typically also vmArg: "-XmxNN" is required. Example: `vmArg: "-Xmx3G", "-Dkafka.prefetch.min.free.mb=300";`
1. Recommendations must be documented for the consumer configuration, for example:
    - reduce max.poll.records
    - reduce fetch.max.bytes
    - use -Dkafka.prefetch.min.free.mb
    - use -Xmx
    - partition isolation (dedicated Java VM)
