### ISSUE TITLE
KafkaConsumer does not allow group management with startPosition BEGINNING, END, or TIME

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.kafka#94]
The KafkaConsumer can be used in a consumer group only with `startPosition: DEFAULT`, but not with BEGINNING, END or TIME.

There is no technical reason for this restriction.
Only with `startPosition: DEFAULT` the operator _subscribes_ to given topics, in all other cases it _assigns_ (manually) to partitions. Subscription is precondition for group management.
When the consumer is subscribed it can seek to the desired positions (Beginning, End, offsets by time) when the partitions are assigned. Assignment is indicated by ConsumerRebalanceListener callback `onPartitionsAssigned`.

Right now, Kafka's group management can only be used when the operator is not part of a consistent region. This will change, however, when #72 (consistent region with consumer group) is implemented. The new CR mode will enable consumer groups with all `startPosition` values  except `Offset`.  The same constraints should apply when the operator does not participate in a consistent region.

More general, the KafkaConsumer should only assign to topic partitions (manually) when the `partition` parameter is specified.

**Comment by ddebrunner** [comment]
@RolefH Can you expand on how this works, with and without consistent region?

When does is startPosition in effect, only the first time Kafka sees the group? Or when the operator starts/restarts?

Just trying to think about failure situations, such as three consumers with two partitions and an active consumer fails, where does the third consumer take over from?

What happens when the consumers are in a UDP region and the width is changed to add more consumers?

**Comment by RolefH** [comment]
### When in CR
**startPosition** is in effect
- when the operator initially starts (job submission)
- when the operator's PE restarts, and the operator is reset to initial state
- when partitions are rebalanced and *unknown* partitions are assigned
    - more explanation: Each operator saves all *assignable* partitions of all topics at startup, It is the sum of all partitions of all topics. Each group member sees a part of them - or nothing. This set goes also into the checkpoint.
    - on partition rebalancing `onPartitionsRevoked` is called first. This triggers a CR reset, when operator has not been reset before or has just subscribed to topics. When `onPartitionsAssigned()` is called, those partitions, which are not in the *assignable* partitions from the checkpoint are seeked to what **startPosition** is.

When an active consumer fails in CR, it gets restarted, and the CR is reset to initial or last consistent state. When restart and reset happens within `session.timeout.ms`, partitions are not rebalanced. The group coordinator node does not notice the outage (must verify this). If partitions are rebalanced after restart and reset, the consumers start fetching at the offsets within the checkpoint - except for *unknown* partitions.
### When not in CR
**startPosition** is in effect
- when the operator initially starts (job submission)
- when the PE is restarted after failure by the runtime. Issue #107. When restart and partition extension happen at the same time, we cannot distinguish between partitions NOT to seek to *startPosition* and partitions the group has never seen before, which should be seeked to *startPosition*.
    - the *assignable* partitions would include also the added partitions when the operator restarts and calls `consumer.partitionsFor (topic)`
- startPosition is in effect when *unkown* partitions are assigned during `onPartitionsAssigned`.
- Offset commit must be reworked for not being in CR: Offsets should be committed in `onPartitionsRevoked` for the currently assigned partitions. Otherwise more records are replayed than necessary when a partition moves from one consumer to another.

When a partition is moved from one consumer to another, the new consumer starts reading from last committed offset. Also when a consumer is kicked out of the group by the group coordinator and re-joins the group later, it starts reading from last committed offset for the assigned partition(s) - but it's also possible to seek within `onPartitionsAssigned`.

**Comment by RolefH** [comment]
Documentation impact in SPL Doc of Kafka and MH toolkit

**Comment by RolefH** [comment]
> ### When not in CR
> 
> **startPosition** is in effect
> 
>  * when the operator initially starts (job submission)
>  * when the PE is restarted after failure by the runtime. Issue #107. When restart and partition extension happen at the same time, we cannot distinguish between partitions NOT to seek to _startPosition_ and partitions the group has never seen before, which should be seeked to _startPosition_.
>  * the _assignable_ partitions would include also the added partitions when the operator restarts and calls `consumer.partitionsFor (topic)`
>  * startPosition is in effect when _unkown_ partitions are assigned during `onPartitionsAssigned`.
>  * Offset commit must be reworked for not being in CR: Offsets should be committed in `onPartitionsRevoked` for the currently assigned partitions. Otherwise more records are replayed than necessary when a partition moves from one consumer to another.
> 
> When a partition is moved from one consumer to another, the new consumer starts reading from last committed offset. Also when a consumer is kicked out of the group by the group coordinator and re-joins the group later, it starts reading from last committed offset for the assigned partition(s) - but it's also possible to seek within `onPartitionsAssigned`.

To support expansion of a parallel region with a group of consumer, an additional mechanism must be implemented. I assume, that a parallel region is extended by
1. stopping the PEs that contain the parallelized operators
2. restart the PEs with the parallelized operators (they will now see the new `maxChannels` value)
With dynamic fusion the restarted PE(s) can contain the operators of the additional parallel channels; with PE isolation, new PEs will be launched.

The `relaunchCount` of a new PE will be 0, so that the operator initialization for new operators looks like an initial start (job submission), where the consumer would seek to *startPosition*. On UDP width expansion, a consumer should not seek a partition to *startPosition* when *the group, i.e. any one consumer of the group* already has committed an offset for the partition.
This coordination between the consumers of the group can be done via an MBean or control variable(s) in the JobControlPlane. This means also, that consumer groups with `startPosition != Default` always require the JCP operator even when not in a CR.

**Comment by RolefH** [comment]
This enhancement changes the behaviour of the KafkaConsumer operator.
I suggest to go to toolkit version 2.0.0 with this enhancement.

**Comment by RolefH** [comment]
fetaure released with toolkit v2.0.0
